# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-22 21:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('image', models.ImageField(upload_to='article/%Y/%m', verbose_name='\u6587\u7ae0\u56fe\u7247')),
                ('url', models.URLField(verbose_name='\u8bbf\u95ee\u5730\u5740')),
                ('author', models.CharField(max_length=20, verbose_name='\u6587\u7ae0\u4f5c\u8005')),
                ('classify', models.CharField(choices=[('rj', '\u65e5\u8bb0'), ('bk', '\u4e2a\u4eba\u64ad\u5ba2'), ('xd', '\u5fc3\u5f97\u7b14\u8bb0')], max_length=10, verbose_name='\u6587\u7ae0\u5206\u7c7b')),
                ('click_num', models.IntegerField(default=0, verbose_name='\u6d4f\u89c8\u91cf')),
                ('comment', models.CharField(max_length=200, verbose_name='\u8bc4\u8bba')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237\u540d')),
            ],
            options={
                'verbose_name': '\u9996\u9875\u6587\u7ae0',
                'verbose_name_plural': '\u9996\u9875\u6587\u7ae0',
            },
        ),
    ]
