# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-22 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexarticle',
            name='comment',
        ),
    ]
