# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-26 12:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0005_auto_20180624_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('image', models.ImageField(upload_to='article/%Y/%m', verbose_name='\u6587\u7ae0\u56fe\u7247')),
                ('url', models.URLField(verbose_name='\u8bbf\u95ee\u5730\u5740')),
                ('author', models.CharField(max_length=20, verbose_name='\u6587\u7ae0\u4f5c\u8005')),
                ('classify', models.CharField(choices=[('rj', '\u65e5\u8bb0'), ('xs', '\u6b23\u8d4f'), ('cx', '\u7a0b\u5e8f\u4eba\u751f'), ('jd', '\u7ecf\u5178\u8bed\u5f55')], default='xs', max_length=10, verbose_name='\u6587\u7ae0\u5206\u7c7b')),
                ('click_num', models.IntegerField(default=0, verbose_name='\u6d4f\u89c8\u91cf')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u9605\u8bfb\u4e66\u7c4d',
                'verbose_name_plural': '\u9605\u8bfb\u4e66\u7c4d',
            },
        ),
        migrations.AlterModelOptions(
            name='articlecomments',
            options={'verbose_name': '\u6587\u7ae0\u8bc4\u8bba', 'verbose_name_plural': '\u6587\u7ae0\u8bc4\u8bba'},
        ),
    ]
